-- NYC Taxi Analytics: business analysis queries
-- Run against warehouse/nyc_taxi.duckdb after `dbt build`.

-- 1) Top pickup zones by revenue and demand
select
    zone,
    borough,
    total_trips,
    total_revenue,
    avg_trip_value,
    avg_revenue_per_mile,
    avg_tip_rate
from marts.mart_zone_performance
order by total_revenue desc
limit 20;

-- 2) Peak demand windows
select
    pickup_weekday,
    pickup_hour,
    total_trips,
    total_revenue
from marts.mart_hourly_demand
order by total_trips desc
limit 20;

-- 3) Airport economics vs regular trips
select
    is_airport_trip,
    count(*) as trips,
    round(avg(total_amount), 2) as avg_trip_value,
    round(avg(trip_distance_miles), 2) as avg_distance,
    round(avg(trip_duration_minutes), 2) as avg_duration,
    round(avg(tip_rate), 4) as avg_tip_rate,
    round(sum(total_amount), 2) as total_revenue
from marts.fct_trips
where trip_quality_flag = 'standard'
group by 1;

-- 4) Revenue concentration: share generated by top 10 pickup zones
with ranked as (
    select
        zone,
        total_revenue,
        row_number() over (order by total_revenue desc) as revenue_rank,
        sum(total_revenue) over () as all_revenue
    from marts.mart_zone_performance
)
select
    round(sum(case when revenue_rank <= 10 then total_revenue else 0 end) / max(all_revenue), 4)
        as top_10_zone_revenue_share
from ranked;

-- 5) Payment-method behavior
select
    payment_type,
    count(*) as trips,
    round(avg(total_amount), 2) as avg_trip_value,
    round(avg(tip_rate), 4) as avg_tip_rate,
    round(sum(total_amount), 2) as total_revenue
from marts.fct_trips
where trip_quality_flag = 'standard'
group by 1
order by trips desc;

-- 6) Daypart economics
select
    daypart,
    count(*) as trips,
    round(avg(total_amount), 2) as avg_trip_value,
    round(avg(trip_duration_minutes), 2) as avg_duration,
    round(avg(revenue_per_mile), 2) as avg_revenue_per_mile,
    round(sum(total_amount), 2) as total_revenue
from marts.fct_trips
where trip_quality_flag = 'standard'
group by 1
order by total_revenue desc;

-- 7) Potential operational inefficiency: slow trips with meaningful distance
select
    pickup_zone,
    dropoff_zone,
    pickup_hour,
    trip_distance_miles,
    trip_duration_minutes,
    round(avg_speed_mph, 2) as avg_speed_mph,
    total_amount
from marts.fct_trips
where trip_quality_flag = 'standard'
  and trip_distance_miles >= 3
  and avg_speed_mph < 5
order by total_amount desc
limit 50;
